language: node_js

notifications:
  email: true

node_js:
  - lts/*

jobs:
  include:
    # Run semantic-release
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
